/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alggentroco;

import com.sun.glass.events.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

/**
 *
 * @author antonio
 */
public class TelaTroco extends javax.swing.JFrame {
    
    private ByteArrayOutputStream baos;
    private PrintStream ps;//Controle da saída do Console
    
    private Troco t1; // Principal
    
    /**
     * Creates new form TelaTroco
     */
    public TelaTroco() {
        t1 = new Troco();
        initComponents();
        
        this.helperSliders();
        criarCapturadeTexto();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBMain = new javax.swing.JLabel();
        jTFValorTroco = new javax.swing.JTextField();
        jLBValorTroco = new javax.swing.JLabel();
        jLBPrcMut = new javax.swing.JLabel();
        jSliderMut = new javax.swing.JSlider();
        jSliderCross = new javax.swing.JSlider();
        jLBPrcCross = new javax.swing.JLabel();
        jTFQuantCromossomos = new javax.swing.JTextField();
        jLBQuantCromossomos = new javax.swing.JLabel();
        jTFPorcentagemCross = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBtnExec = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLBTituloS = new javax.swing.JLabel();
        jTFNumGeracoes = new javax.swing.JTextField();
        jLBNumGer = new javax.swing.JLabel();
        jTFPorcentagemMut = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFAleatInicial = new javax.swing.JTextField();
        jLBAleat = new javax.swing.JLabel();
        jBtnGraficoMelhoresCrm = new javax.swing.JButton();
        jLBTituloE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLBMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLBMain.setText("Troco - Mático");

        jLBValorTroco.setText("Valor do Troco");

        jLBPrcMut.setText("Porcentagem Mutação");

        jSliderMut.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderMutStateChanged(evt);
            }
        });

        jSliderCross.setMinimum(1);
        jSliderCross.setMinorTickSpacing(1);
        jSliderCross.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderCrossStateChanged(evt);
            }
        });

        jLBPrcCross.setText("Porcentagem Crossover");

        jLBQuantCromossomos.setText("Quantidade de Cromossomos");

        jTFPorcentagemCross.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFPorcentagemCrossKeyPressed(evt);
            }
        });

        jLabel6.setText("%");

        jBtnExec.setText("Executar Algoritmo");
        jBtnExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExecActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setViewportView(jScrollPane1);

        jLBTituloS.setText("Saída");

        jLBNumGer.setText("Número de Gerações (0 p/ uso da Heurísitica)");

        jTFPorcentagemMut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFPorcentagemMutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFPorcentagemMutKeyReleased(evt);
            }
        });

        jLabel9.setText("%");

        jLBAleat.setText("Aleatoriedade Inicial");

        jBtnGraficoMelhoresCrm.setText("Gráfico");
        jBtnGraficoMelhoresCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGraficoMelhoresCrmActionPerformed(evt);
            }
        });

        jLBTituloE.setText("Entradas do Problema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLBTituloS)
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLBMain))
                            .addComponent(jLBPrcCross)
                            .addComponent(jLBPrcMut)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLBTituloE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jSliderMut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFPorcentagemMut))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jSliderCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFPorcentagemCross, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBQuantCromossomos)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTFNumGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFQuantCromossomos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnExec))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLBNumGer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLBValorTroco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnGraficoMelhoresCrm)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFAleatInicial)
                        .addGap(586, 586, 586))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBAleat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBMain)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBTituloS)
                    .addComponent(jLBTituloE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLBPrcCross)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTFPorcentagemCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(15, 15, 15)
                        .addComponent(jLBPrcMut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSliderMut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTFPorcentagemMut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(29, 29, 29)
                        .addComponent(jLBQuantCromossomos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFQuantCromossomos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLBNumGer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNumGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLBAleat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFAleatInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGraficoMelhoresCrm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jBtnExec)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderCrossStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderCrossStateChanged
        // TODO add your handling code here:
        this.jTFPorcentagemCross.setText(Integer.toString(this.jSliderCross.getValue()));//Linkar um no outro
        
    }//GEN-LAST:event_jSliderCrossStateChanged

    private void jTFPorcentagemCrossKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPorcentagemCrossKeyPressed

        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(Integer.parseInt(this.jTFPorcentagemCross.getText()) > 1 && Integer.parseInt(this.jTFPorcentagemCross.getText())<=100){
                this.jSliderCross.setValue(Integer.parseInt(this.jTFPorcentagemCross.getText()));
            }
        }
    }//GEN-LAST:event_jTFPorcentagemCrossKeyPressed

    private void jBtnExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExecActionPerformed
        // TODO add your handling code here:
        //Opção de reset aqui
        t1 = new Troco();
        this.construcaoProblema();
        t1.driver();
        this.jTextArea1.setText(baos.toString());
    }//GEN-LAST:event_jBtnExecActionPerformed

    private void jSliderMutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderMutStateChanged
        // TODO add your handling code here:
        this.jTFPorcentagemMut.setText(Integer.toString(this.jSliderMut.getValue()));
    }//GEN-LAST:event_jSliderMutStateChanged

    private void jTFPorcentagemMutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPorcentagemMutKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPorcentagemMutKeyReleased

    private void jTFPorcentagemMutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPorcentagemMutKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(Integer.parseInt(this.jTFPorcentagemMut.getText()) > 1 && Integer.parseInt(this.jTFPorcentagemMut.getText()) <= 100){
                this.jSliderMut.setValue(Integer.parseInt(this.jTFPorcentagemMut.getText()));
            
            }
        }
    }//GEN-LAST:event_jTFPorcentagemMutKeyPressed

    private void jBtnGraficoMelhoresCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGraficoMelhoresCrmActionPerformed
        // TODO add your handling code here:
        GraficoAGTroco a1 = new GraficoAGTroco("Gráfico de Resultados", this.t1.getMediaMelhoresGeracoes(), this.t1.getMelhoresSelecoes(), this.t1.getValortrocoT());
        a1.constroiGrafico(this.t1.getMediaMelhoresGeracoes(), this.t1.getMelhoresSelecoes(), this.t1.getValortrocoT());
    }//GEN-LAST:event_jBtnGraficoMelhoresCrmActionPerformed

    public void criarCapturadeTexto(){
        baos = new ByteArrayOutputStream();
        ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        
//        for(int i = 0; i<1000; i++){
//            System.out.println("Pato\n");
//        }
    
    
    
    
    }
    
    public void helperSliders(){
        this.jTFPorcentagemCross.setText("50");
        this.jTFPorcentagemMut.setText("50");
    
    
    }
    
    public void construcaoProblema(){
        try{
            if(this.jTFValorTroco.getText() != ""){
                this.t1.setValortrocoT(Integer.parseInt(this.jTFValorTroco.getText()));
                //System.out.println(this.t1.getValortrocoT());
            }
            
            this.t1.setPorcentagemcrossover(Double.parseDouble(this.jTFPorcentagemCross.getText()));
            this.t1.setPorcentagemmutacao(Double.parseDouble(this.jTFPorcentagemMut.getText()));
            this.t1.setQuantCromossomos(Integer.parseInt(this.jTFQuantCromossomos.getText()));
            this.t1.setInicialAleatorio(Integer.parseInt(this.jTFAleatInicial.getText()));
            
            //this.t1.heurGeracoes(true);
            
            if(this.jTFNumGeracoes.getText().equals("0")){
                this.t1.heurGeracoes(true);
            }else{
                this.t1.setGeracoes(Integer.parseInt(this.jTFNumGeracoes.getText()));
            
            }            
        }catch(Exception e){


        }
    
    
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaTroco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaTroco().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExec;
    private javax.swing.JButton jBtnGraficoMelhoresCrm;
    private javax.swing.JLabel jLBAleat;
    private javax.swing.JLabel jLBMain;
    private javax.swing.JLabel jLBNumGer;
    private javax.swing.JLabel jLBPrcCross;
    private javax.swing.JLabel jLBPrcMut;
    private javax.swing.JLabel jLBQuantCromossomos;
    private javax.swing.JLabel jLBTituloE;
    private javax.swing.JLabel jLBTituloS;
    private javax.swing.JLabel jLBValorTroco;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderCross;
    private javax.swing.JSlider jSliderMut;
    private javax.swing.JTextField jTFAleatInicial;
    private javax.swing.JTextField jTFNumGeracoes;
    private javax.swing.JTextField jTFPorcentagemCross;
    private javax.swing.JTextField jTFPorcentagemMut;
    private javax.swing.JTextField jTFQuantCromossomos;
    private javax.swing.JTextField jTFValorTroco;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
